import '../../../features/employees/data/models/employee_model.dart';

/// Dummy data for development and testing
class DummyData {
  DummyData._();

  static final List<Employee> employees = [
    Employee(
      id: '1',
      employeeCode: 'EMP001',
      firstName: 'Rajesh',
      lastName: 'Kumar',
      email: 'rajesh.kumar@company.com',
      phone: '9876543210',
      employeeType: 'office',
      department: 'Engineering',
      designation: 'Senior Engineer',
      joiningDate: DateTime(2021, 3, 15),
      confirmationDate: DateTime(2021, 6, 15),
      dateOfBirth: DateTime(1988, 7, 22),
      gender: 'Male',
      status: 'active',
      bankName: 'HDFC Bank',
      bankAccountNumber: '12345678901234',
      ifscCode: 'HDFC0001234',
      panNumber: 'ABCDE1234F',
      aadhaarNumber: '123456789012',
      isPfApplicable: true,
      isEsicApplicable: false,
      createdAt: DateTime.now().subtract(const Duration(days: 365)),
      updatedAt: DateTime.now(),
    ),
    Employee(
      id: '2',
      employeeCode: 'EMP002',
      firstName: 'Priya',
      lastName: 'Sharma',
      email: 'priya.sharma@company.com',
      phone: '9876543211',
      employeeType: 'office',
      department: 'Human Resources',
      designation: 'HR Manager',
      joiningDate: DateTime(2020, 1, 10),
      confirmationDate: DateTime(2020, 4, 10),
      dateOfBirth: DateTime(1990, 11, 5),
      gender: 'Female',
      status: 'active',
      isPfApplicable: true,
      isEsicApplicable: false,
      createdAt: DateTime.now().subtract(const Duration(days: 730)),
      updatedAt: DateTime.now(),
    ),
    Employee(
      id: '3',
      employeeCode: 'EMP003',
      firstName: 'Amit',
      lastName: 'Patel',
      email: 'amit.patel@company.com',
      phone: '9876543212',
      employeeType: 'factory',
      department: 'Production',
      designation: 'Supervisor',
      joiningDate: DateTime(2022, 6, 1),
      confirmationDate: DateTime(2022, 9, 1),
      dateOfBirth: DateTime(1985, 2, 14),
      gender: 'Male',
      status: 'active',
      isPfApplicable: true,
      isEsicApplicable: true,
      createdAt: DateTime.now().subtract(const Duration(days: 200)),
      updatedAt: DateTime.now(),
    ),
    Employee(
      id: '4',
      employeeCode: 'EMP004',
      firstName: 'Sneha',
      lastName: 'Reddy',
      email: 'sneha.reddy@company.com',
      phone: '9876543213',
      employeeType: 'office',
      department: 'Finance & Accounts',
      designation: 'Senior Accountant',
      joiningDate: DateTime(2019, 8, 20),
      confirmationDate: DateTime(2019, 11, 20),
      dateOfBirth: DateTime(1992, 4, 30),
      gender: 'Female',
      status: 'active',
      isPfApplicable: true,
      isEsicApplicable: false,
      createdAt: DateTime.now().subtract(const Duration(days: 900)),
      updatedAt: DateTime.now(),
    ),
    Employee(
      id: '5',
      employeeCode: 'EMP005',
      firstName: 'Vikram',
      lastName: 'Singh',
      email: 'vikram.singh@company.com',
      phone: '9876543214',
      employeeType: 'factory',
      department: 'Production',
      designation: 'Operator',
      joiningDate: DateTime(2023, 1, 5),
      dateOfBirth: DateTime(1995, 9, 12),
      gender: 'Male',
      status: 'active',
      isPfApplicable: false,
      isEsicApplicable: true,
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      updatedAt: DateTime.now(),
    ),
    Employee(
      id: '6',
      employeeCode: 'EMP006',
      firstName: 'Neha',
      lastName: 'Gupta',
      email: 'neha.gupta@company.com',
      phone: '9876543215',
      employeeType: 'office',
      department: 'Sales & Marketing',
      designation: 'Marketing Executive',
      joiningDate: DateTime(2022, 11, 15),
      dateOfBirth: DateTime(1994, 6, 18),
      gender: 'Female',
      status: 'active',
      isPfApplicable: false,
      isEsicApplicable: false,
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
      updatedAt: DateTime.now(),
    ),
    Employee(
      id: '7',
      employeeCode: 'EMP007',
      firstName: 'Rahul',
      lastName: 'Verma',
      email: 'rahul.verma@company.com',
      phone: '9876543216',
      employeeType: 'factory',
      department: 'Quality Control',
      designation: 'QC Inspector',
      joiningDate: DateTime(2021, 9, 1),
      confirmationDate: DateTime(2021, 12, 1),
      dateOfBirth: DateTime(1991, 12, 25),
      gender: 'Male',
      status: 'inactive',
      isPfApplicable: true,
      isEsicApplicable: true,
      createdAt: DateTime.now().subtract(const Duration(days: 500)),
      updatedAt: DateTime.now(),
    ),
    Employee(
      id: '8',
      employeeCode: 'EMP008',
      firstName: 'Anita',
      lastName: 'Joshi',
      email: 'anita.joshi@company.com',
      phone: '9876543217',
      employeeType: 'office',
      department: 'Administration',
      designation: 'Admin Executive',
      joiningDate: DateTime(2020, 5, 10),
      confirmationDate: DateTime(2020, 8, 10),
      dateOfBirth: DateTime(1993, 3, 8),
      gender: 'Female',
      status: 'active',
      isPfApplicable: true,
      isEsicApplicable: false,
      createdAt: DateTime.now().subtract(const Duration(days: 600)),
      updatedAt: DateTime.now(),
    ),
    Employee(
      id: '9',
      employeeCode: 'EMP009',
      firstName: 'Suresh',
      lastName: 'Yadav',
      email: 'suresh.yadav@company.com',
      phone: '9876543218',
      employeeType: 'factory',
      department: 'Maintenance',
      designation: 'Technician',
      joiningDate: DateTime(2022, 3, 20),
      confirmationDate: DateTime(2022, 6, 20),
      dateOfBirth: DateTime(1987, 8, 15),
      gender: 'Male',
      status: 'active',
      isPfApplicable: true,
      isEsicApplicable: true,
      createdAt: DateTime.now().subtract(const Duration(days: 300)),
      updatedAt: DateTime.now(),
    ),
    Employee(
      id: '10',
      employeeCode: 'EMP010',
      firstName: 'Kavita',
      lastName: 'Mehta',
      email: 'kavita.mehta@company.com',
      phone: '9876543219',
      employeeType: 'office',
      department: 'Engineering',
      designation: 'Team Lead',
      joiningDate: DateTime(2018, 10, 1),
      confirmationDate: DateTime(2019, 1, 1),
      dateOfBirth: DateTime(1986, 1, 20),
      gender: 'Female',
      status: 'active',
      isPfApplicable: true,
      isEsicApplicable: false,
      reportingManager: 'Rajesh Kumar',
      createdAt: DateTime.now().subtract(const Duration(days: 1200)),
      updatedAt: DateTime.now(),
    ),
  ];

  // Dashboard Stats
  static int get totalEmployees => employees.length;
  static int get officeEmployees => employees.where((e) => e.isOffice).length;
  static int get factoryEmployees => employees.where((e) => e.isFactory).length;
  static int get activeEmployees => employees.where((e) => e.isActive).length;
  static int get inactiveEmployees =>
      employees.where((e) => !e.isActive).length;
  static int get pendingApprovals => 5;
  static double get salaryProcessed => 1250000.0;
  static int get pfPending => 3;
  static int get esicPending => 2;

  // Monthly attendance data for charts
  static List<Map<String, dynamic>> get monthlyAttendance => [
    {'month': 'Jan', 'present': 92, 'absent': 8},
    {'month': 'Feb', 'present': 88, 'absent': 12},
    {'month': 'Mar', 'present': 95, 'absent': 5},
    {'month': 'Apr', 'present': 90, 'absent': 10},
    {'month': 'May', 'present': 93, 'absent': 7},
    {'month': 'Jun', 'present': 89, 'absent': 11},
  ];

  // Monthly salary expense for charts
  static List<Map<String, dynamic>> get monthlySalaryExpense => [
    {'month': 'Jan', 'amount': 1100000},
    {'month': 'Feb', 'amount': 1150000},
    {'month': 'Mar', 'amount': 1200000},
    {'month': 'Apr', 'amount': 1180000},
    {'month': 'May', 'amount': 1220000},
    {'month': 'Jun', 'amount': 1250000},
  ];

  // Department distribution
  static Map<String, int> get departmentDistribution => {
    'Engineering': 3,
    'Production': 2,
    'Human Resources': 1,
    'Finance': 1,
    'Sales & Marketing': 1,
    'Administration': 1,
    'Quality Control': 1,
  };

  // Recent activities
  static List<Map<String, dynamic>> get recentActivities => [
    {
      'action': 'New Employee Added',
      'description': 'Vikram Singh joined as Operator',
      'time': '2 hours ago',
      'type': 'add',
    },
    {
      'action': 'Salary Processed',
      'description': 'June 2024 salary processed for 10 employees',
      'time': '1 day ago',
      'type': 'payment',
    },
    {
      'action': 'Offer Letter Sent',
      'description': 'Offer letter sent to Ravi Teja',
      'time': '2 days ago',
      'type': 'document',
    },
    {
      'action': 'Leave Approved',
      'description': 'Casual leave approved for Priya Sharma',
      'time': '3 days ago',
      'type': 'approval',
    },
    {
      'action': 'Document Uploaded',
      'description': 'Aadhaar card uploaded for Neha Gupta',
      'time': '4 days ago',
      'type': 'upload',
    },
  ];

  // Pending tasks
  static List<Map<String, dynamic>> get pendingTasks => [
    {
      'title': 'Approve Leave Request',
      'description': 'Amit Patel - Casual Leave (2 days)',
      'priority': 'high',
      'dueDate': 'Today',
    },
    {
      'title': 'Generate Salary Slips',
      'description': 'June 2024 salary slips pending',
      'priority': 'medium',
      'dueDate': 'Tomorrow',
    },
    {
      'title': 'Review Offer Letter',
      'description': 'New hire - Software Developer position',
      'priority': 'high',
      'dueDate': 'Today',
    },
    {
      'title': 'PF Submission',
      'description': 'Monthly PF challan submission',
      'priority': 'medium',
      'dueDate': 'In 3 days',
    },
    {
      'title': 'Update KYC Documents',
      'description': '3 employees have pending KYC',
      'priority': 'low',
      'dueDate': 'In 5 days',
    },
  ];
}
